# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69c71bb750382a0abbd9f8a2c3a301645c1a5373334b1f975d0cd17bc74b6438c4cda0dcfed727a38c615413240be08a1cdd97818ffe19336495b1fdb241f056

test:
  secret_key_base: 58cb4b1e0dfa7b94ef76bc360314ce47c729da5c9c2e37131c20671f649d7b73d690cd8a285b8372fd0bdc1822917bd2617d9d01c087252fccbaa9387bec7790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
